// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAX3y-Hw9DZMx9EmuoEIcvmiHKRo1Uk37Y',
    appId: '1:370887599189:web:9a93de27ba6ad88eb920dc',
    messagingSenderId: '370887599189',
    projectId: 'igor-alish',
    authDomain: 'igor-alish.firebaseapp.com',
    storageBucket: 'igor-alish.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHBHhlh_D05qcFV8EZvHMEMPoHDnNZqng',
    appId: '1:370887599189:android:bfd4394c2e12ae5bb920dc',
    messagingSenderId: '370887599189',
    projectId: 'igor-alish',
    storageBucket: 'igor-alish.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVNcm0A4pATnQ2DPeHq5C5ohZYs1RMDjc',
    appId: '1:370887599189:ios:a50a39c6672a080fb920dc',
    messagingSenderId: '370887599189',
    projectId: 'igor-alish',
    storageBucket: 'igor-alish.firebasestorage.app',
    iosBundleId: 'com.example.eventPlanner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVNcm0A4pATnQ2DPeHq5C5ohZYs1RMDjc',
    appId: '1:370887599189:ios:a50a39c6672a080fb920dc',
    messagingSenderId: '370887599189',
    projectId: 'igor-alish',
    storageBucket: 'igor-alish.firebasestorage.app',
    iosBundleId: 'com.example.eventPlanner',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAX3y-Hw9DZMx9EmuoEIcvmiHKRo1Uk37Y',
    appId: '1:370887599189:web:d9d877160724c3c7b920dc',
    messagingSenderId: '370887599189',
    projectId: 'igor-alish',
    authDomain: 'igor-alish.firebaseapp.com',
    storageBucket: 'igor-alish.firebasestorage.app',
  );
}
